title: The world of dreams
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  We will be grateful if you could tell us your last beatiful dreams.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
